### ISSUE TITLE
我替换成 deepspeech-0.9.2-models.pbmm会报错

### ISSUE THREAD

**Issue by tailangjun** [sstzal/DFRF#36]
感觉默认的 deepspeech是v0.1，我就换成 0.9.2或者 0.9.3，都会报错

Traceback (most recent call last):
  File "/home/tailangjun/Documents/AIGenHuman/NerfLips/DFRF/data_util/deepspeech_features/extract_ds_features.py", line 133, in <module>
    main()
  File "/home/tailangjun/Documents/AIGenHuman/NerfLips/DFRF/data_util/deepspeech_features/extract_ds_features.py", line 125, in main
    extract_features(
  File "/home/tailangjun/Documents/AIGenHuman/NerfLips/DFRF/data_util/deepspeech_features/extract_ds_features.py", line 82, in extract_features
    conv_audios_to_deepspeech(
  File "/home/tailangjun/Documents/AIGenHuman/NerfLips/DFRF/data_util/deepspeech_features/deepspeech_features.py", line 41, in conv_audios_to_deepspeech
    graph, logits_ph, input_node_ph, input_lengths_ph = prepare_deepspeech_net(
  File "/home/tailangjun/Documents/AIGenHuman/NerfLips/DFRF/data_util/deepspeech_features/deepspeech_features.py", line 102, in prepare_deepspeech_net
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'

请问是不是要修改啥代码呀

**Comment by beria-moon** [comment]
请问你解决了吗

**Comment by tailangjun** [comment]
> 请问你解决了吗

我使用 pbmm_to_pb.py可以将 pbmm转换pb，但是维度上会报错

deepspeech-0.1.0
Tensor("deepspeech/logits:0", shape=(?, ?, 29), dtype=float32)
正常输出 (120, 29)

deepspeech-0.8.2
Tensor("deepspeech/logits:0", shape=(16, 1, 29), dtype=float32)
ValueError: Cannot feed value of shape (1, 240, 494) for Tensor 'deepspeech/input_node:0', which has shape '(1, 16, 19, 26)'

deepspeech-0.9.3
Tensor("deepspeech/logits:0", shape=(16, 1, 256), dtype=float32)
ValueError: Cannot feed value of shape (1, 240, 494) for Tensor 'deepspeech/input_node:0', which has shape '(1, 16, 19, 26)'

**Comment by beria-moon** [comment]
我用的0.1.0
输出是（16，29，1）




894269281
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sstzal/DFRF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月25日(星期四) 中午12:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sstzal/DFRF] 我替换成 deepspeech-0.9.2-models.pbmm会报错 (Issue #36)





  
请问你解决了吗
  
我使用 pbmm_to_pb.py可以将 pbmm转换pb，但是维度上会报错
 
deepspeech-0.1.0
 Tensor("deepspeech/logits:0", shape=(?, ?, 29), dtype=float32)
 正常输出 (120, 29)
 
deepspeech-0.8.2
 Tensor("deepspeech/logits:0", shape=(16, 1, 29), dtype=float32)
 ValueError: Cannot feed value of shape (1, 240, 494) for Tensor 'deepspeech/input_node:0', which has shape '(1, 16, 19, 26)'
 
deepspeech-0.9.3
 Tensor("deepspeech/logits:0", shape=(16, 1, 256), dtype=float32)
 ValueError: Cannot feed value of shape (1, 240, 494) for Tensor 'deepspeech/input_node:0', which has shape '(1, 16, 19, 26)'

**Comment by tailangjun** [comment]
> 我用的0.1.0 输出是（16，29，1） 894269281 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sstzal/DFRF" ***@***.***&gt;; 发送时间:&nbsp;2024年4月25日(星期四) 中午12:43 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [sstzal/DFRF] 我替换成 deepspeech-0.9.2-models.pbmm会报错 (Issue #36) 请问你解决了吗 我使用 pbmm_to_pb.py可以将 pbmm转换pb，但是维度上会报错 deepspeech-0.1.0 Tensor("deepspeech/logits:0", shape=(?, ?, 29), dtype=float32) 正常输出 (120, 29) deepspeech-0.8.2 Tensor("deepspeech/logits:0", shape=(16, 1, 29), dtype=float32) ValueError: Cannot feed value of shape (1, 240, 494) for Tensor 'deepspeech/input_node:0', which has shape '(1, 16, 19, 26)' deepspeech-0.9.3 Tensor("deepspeech/logits:0", shape=(16, 1, 256), dtype=float32) ValueError: Cannot feed value of shape (1, 240, 494) for Tensor 'deepspeech/input_node:0', which has shape '(1, 16, 19, 26)' — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

估计是对 network_output的处理方式不太一样
```python
            network_output = sess.run(
                self.logits_ph,
                feed_dict={
                    self.input_node_ph: input_vector[np.newaxis, ...],
                    self.input_lengths_ph: [input_vector.shape[0]]})'
            
            ds_features = network_output[::2,0,:]
```
AD-NeRF、DFRF、ER-NeRF在这块也是有点不同的
